services:
  - type: web
    name: complaint-project7
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn complaint_project7.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: complaint-db
          property: connectionString

databases:
  - name: complaint-db
    databaseName: complaint_db
    user: complaint_user
